name: sim2real_component_classification
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch>=2.1.0
      - torchvision>=0.16.0
      - torchaudio>=2.1.0
      - numpy>=1.24.0
      - matplotlib>=3.7.0
      - seaborn>=0.12.2
      - scikit-learn>=1.3.0
      - opencv-python>=4.8.0
      - jupyterlab>=4.2.0
      - notebook>=7.2.0
      - pandas>=2.1.0
      - tqdm>=4.66.0
